spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: ${DATABASE_URL}
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            max-lifetime: 1800000
            connection-timeout: 30000
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: update
logging:
    level:
        root: INFO