spring:
    config:
        activate:
            on-profile: prd
    datasource:
        url: ${DATABASE_URL}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            max-lifetime: 1800000
            connection-timeout: 30000
    jpa:
        database: postgresql
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        hibernate:
            ddl-auto: create
logging:
    level:
        root: INFO